# Generated by Django 5.1.1 on 2024-09-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('restaurant', '0002_alter_modifier_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodifier',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_modifiers', to='app.orderitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemmodifier',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AddConstraint(
            model_name='orderitemmodifier',
            constraint=models.UniqueConstraint(fields=('order', 'item', 'modifier'), name='unique_order_item_modifier'),
        ),
    ]
