# Generated by Django 5.1.1 on 2024-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderitemmodifier_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered')], default='not_paid', max_length=10),
        ),
    ]
